# Generated by Django 3.2.3 on 2021-06-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordform",
            name="linguist_info_stem",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
